### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by cyril3** [CYRO4S/Universal-Linux-Script#3]
1. 如果是命令替换的话，我建议使用alias命令设置别名这样的方法。这样可以从系统层面直接支持ULS的主要功能，提升效率（不需要在运行前使用字符串替换了），不仅支持脚本里命令替换，在命令行里也适用。  
2. 现在获取IP地址的方法只能获取公网IP，不能获取内网IP。  
3. 运行安装脚本如果没有管理员权限，安装会失败。  
4. 有些安装包的apt-get 和 yum下面的包名不一样，能否在git上维护一份映射表，使包名统一起来就更加方便了。  
5. 执行完脚本之后，应该返回其返回值，而不应该简单得返回0.

**Comment by playercatboy** [comment]
建议1： Won't fix. ULS 不仅是替换命令，还有预置的系统信息变量，这是最关键的。这部分在alias里不好进行。  同时，我希望能最小化对用户设备的更改。alias是用户私人领域，修改这个不太好。。
建议4：Question. 该安装那个包脚本撰写者应该比我清楚。
后面的问题，会采纳。该issue将在完成后关闭。

**Comment by playercatboy** [comment]
建议5：现已完成 & committed。  
建议2：现已完成 & committed。Wiki 已更新。
建议3：完成 & committed。Wiki 已更新。
建议4：会新增一个页面帮助脚本撰写者决定。    
ULS现达到里程碑1，感谢建议。

**Comment by cyril3** [comment]
问题1：
我仍然觉得alias更适合。因为alias起的命令别名并不会影响原命令，卸载的时候可以删除就行。所以我觉得不会有影响。至于系统信息变量，可以使用环境变量来记录。
