### ISSUE TITLE
update的BUG

### ISSUE THREAD

**Issue by cyril3** [CYRO4S/Universal-Linux-Script#4]
在连不上网的情况下，升级会直接卸载ULS。- -！

**Comment by playercatboy** [comment]
首先，若没有网路连线，```Update()``` 中的 ```wget -O ...``` 也无法执行啊，删除操作是在```uls_update.sh```中定义的。  
不过，我已在```Update()```中执行命令前添加了判断有没有网路连线的方法了，若没有网路连线，提示并退出。感谢提出issue。    
代码已完成，等待下一次commit。

**Comment by cyril3** [comment]
考虑这种情况：uls_update.sh下载成功。但是脚本的wget下载失败了，怎么办……
我觉得应该先下载，下载成功后直接替换就好。

**Comment by playercatboy** [comment]
uls_update.sh fixed.
