### ISSUE TITLE
多进程可能引发冲突

### ISSUE THREAD

**Issue by cyril3** [CYRO4S/Universal-Linux-Script#5]
现在的实现方法是把修改后的脚本放入/tmp/目录。但是脚本的路径是固定的。在多进程的情况家会有比较小的概率发生冲突。这个问题我只是根据代码思考的，并没有运行验证。
建议使用python 的tempfile模块。

**Comment by playercatboy** [comment]
临时文件工作模式已更改为TemporaryFile()，等待下次Commit。
