### ISSUE TITLE
系统环境变更的情况

### ISSUE THREAD

**Issue by cyril3** [CYRO4S/Universal-Linux-Script#9]
当系统环境出现变更，例如主机通过DHCP获取IP，但是IP变化了。/usr/share/uls/device.json中保存的仍然是旧的IP。这种情况也许会出现问题。

**Comment by playercatboy** [comment]
我的教程里有写。。。可能没有同步到Wiki。[安装与使用ULS](https://github.com/CYRO4S/Universal-Linux-Script/wiki/%E5%AE%89%E8%A3%85%E4%B8%8E%E4%BD%BF%E7%94%A8ULS#%E9%87%8D%E6%96%B0%E8%BF%90%E8%A1%8C%E7%B3%BB%E7%BB%9F%E4%BF%A1%E6%81%AF%E8%8E%B7%E5%8F%96)

**Comment by cyril3** [comment]
问题的关键是，DHCP的情况下，用户可能根本注意不到IP变化了。
